// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    [Migration("20210129212641_lastMig")]
    partial class lastMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WebApplication1.Models.Medicament", b =>
                {
                    b.Property<int?>("IdMedicament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMedicament");

                    b.ToTable("Medicaments");

                    b.HasData(
                        new
                        {
                            IdMedicament = 1,
                            Description = "pfisier",
                            Name = "covid-19-vac",
                            Type = "vac"
                        },
                        new
                        {
                            IdMedicament = 2,
                            Description = "modena",
                            Name = "covid-21-vac",
                            Type = "antivac"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("WebApplication1.Models.Prescription", b =>
                {
                    b.Property<int?>("IdPrescrition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdDoctor")
                        .HasColumnType("int");

                    b.HasKey("IdPrescrition");

                    b.HasIndex("ClientId");

                    b.HasIndex("IdDoctor");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("WebApplication1.Models.Prescrition_Medicament", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dose")
                        .HasColumnType("int");

                    b.Property<int?>("IdMedicament")
                        .HasColumnType("int");

                    b.Property<int?>("IdPrescrtiption")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("IdMedicament");

                    b.HasIndex("IdPrescrtiption");

                    b.ToTable("Prescrition_Medicament");
                });

            modelBuilder.Entity("WebApplication1.Models.Client", b =>
                {
                    b.HasBaseType("WebApplication1.Models.Person");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Client");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Joe",
                            LastName = "Doe",
                            Birthdate = new DateTime(2021, 1, 29, 22, 26, 40, 778, DateTimeKind.Local).AddTicks(6535)
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Andrzej",
                            LastName = "Chuda",
                            Birthdate = new DateTime(2021, 1, 29, 22, 26, 40, 781, DateTimeKind.Local).AddTicks(8813)
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Andrzej",
                            LastName = "Łachuda",
                            Birthdate = new DateTime(2021, 1, 29, 22, 26, 40, 781, DateTimeKind.Local).AddTicks(8857)
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Doctor", b =>
                {
                    b.HasBaseType("WebApplication1.Models.Person");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            FirstName = "Doktor",
                            LastName = "Etker",
                            Email = "doEtkter@dr.pl"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Dok",
                            LastName = "Tor",
                            Email = "dtor@dr.pl"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Grigory",
                            LastName = "Haus",
                            Email = "dr.hous@dr.pl"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Prescription", b =>
                {
                    b.HasOne("WebApplication1.Models.Client", "Client")
                        .WithMany("Prescriptions")
                        .HasForeignKey("ClientId");

                    b.HasOne("WebApplication1.Models.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("IdDoctor");

                    b.Navigation("Client");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("WebApplication1.Models.Prescrition_Medicament", b =>
                {
                    b.HasOne("WebApplication1.Models.Medicament", "Medicament")
                        .WithMany("all")
                        .HasForeignKey("IdMedicament");

                    b.HasOne("WebApplication1.Models.Prescription", "Prescription")
                        .WithMany("all")
                        .HasForeignKey("IdPrescrtiption");

                    b.Navigation("Medicament");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("WebApplication1.Models.Medicament", b =>
                {
                    b.Navigation("all");
                });

            modelBuilder.Entity("WebApplication1.Models.Prescription", b =>
                {
                    b.Navigation("all");
                });

            modelBuilder.Entity("WebApplication1.Models.Client", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("WebApplication1.Models.Doctor", b =>
                {
                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
